### ISSUE TITLE
Adding apps via Playstore links directly for 

### ISSUE THREAD

**Issue by s4ndeeps** [ajinabraham/Mobile-Security-Framework-MobSF#142]
- allowing to add apps via play-store links will be more easier !

**Comment by ajinabraham** [comment]
This functionality can be added, but highly unstable as it breaks when play store is updated

**Comment by s4ndeeps** [comment]
yeah, adding it as optional way to add apps , will be good only , hope so !

**Comment by bugwrangler** [comment]
I've been using https://github.com/egirault/googleplay-api since last 6 months, it has been working without error so far in case you would like to check out. 
<img width="1273" alt="screen shot 2016-05-10 at 12 52 33 am" src="https://cloud.githubusercontent.com/assets/6933052/15125264/80c72aaa-1649-11e6-9636-d9bd90331fd6.png">

**Comment by ajinabraham** [comment]
Thanks for pointing out

**Comment by ajinabraham** [comment]
Not consistent. Won't implement
