### ISSUE TITLE
How to enable network signal service or high signal strength in MobSF VM?

### ISSUE THREAD

**Issue by sam2u** [ajinabraham/Mobile-Security-Framework-MobSF#169]
Hi ajinabraham,
Firstly, I'd like to thank you for creating such an awesome and useful android security testing tool.
Secondly, I'm facing an issue running a target .apk file which does not work in the MobSF VM emulator. Due to this am not able to progress with the MobSF Dynamic Analysis. 

FYI: MobSF Static Analysis works fine and I'm also able to browse the internet on the MobSF VM so no issues with the internet network settings otherwise.

My best guess is possibly target application maybe detecting lack of network signal service or weak signal strength (0dBm) in MobSF VM as one of its feature is about PSTN calling. However I've tried to run the same target application by installing in the standard Android Studio emulator/ AVD and application works fine. 

So can you please help and guide me on how to enable network signal service or high signal strength in MobSF VM. 
![mobsf network no signal strength](https://cloud.githubusercontent.com/assets/19683416/15703518/617cc1b6-2803-11e6-8abd-62b5e3778153.png)

![mobsf network no signal strength 2](https://cloud.githubusercontent.com/assets/19683416/15705983/155a323a-280f-11e6-91f5-4114f21001c7.png)

**Comment by ajinabraham** [comment]
I think you might need to write an Xposed module to fake these details
You can also give a try to these Xposed modules. I am not sure if these can help. Let me know if it helps.
http://repo.xposed.info/module/com.gnufabio.simeditor
http://repo.xposed.info/module/com.beatslayer.xposedmod.netstrength
http://repo.xposed.info/module/com.ceco.kitkat.gravitybox

Another easy solution is to use a rooted android device for analysis instead of the VM.

**Comment by sam2u** [comment]
Thanks. Will surely give it a try or as suggested option otherwise.
