### ISSUE TITLE
osx el captain build 

### ISSUE THREAD

**Issue by the1220** [ajinabraham/Mobile-Security-Framework-MobSF#247]
ImportError: No module named django.core.management

**Comment by the1220** [comment]
Here is the full error message: 
File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

**Comment by ajinabraham** [comment]
This is not a MobSF issue. Please read this before opening issues: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/CONTRIBUTING.md#using-the-issue-tracker

Now your problem is that Django is not installed correctly.

**Comment by TiberiumPY** [comment]
@the1220 you need to install django

**Comment by kevinpiac** [comment]
I know it's an old issue but I had the same today. 
As @ajinabraham said it's not related to MobSF. The problem is that django is either not well installed or at least the script can not use it. 

If you have install (like me) dependencies using `sudo` command, be sure to run the MobSF's server using `sudo` too : `sudo python manage.py runserver`. 

If this does not fix your issue, [this page](https://stackoverflow.com/questions/14013728/django-no-module-named-django-core-management) contains other useful answers.
