### ISSUE TITLE
[windows_static] appxbundle

### ISSUE THREAD

**Issue by lucacapacci** [ajinabraham/Mobile-Security-Framework-MobSF#254]
Hi, I read windows support is limited to appx files. I was wondering if appxbundle files are ok too..

**Comment by ajinabraham** [comment]
@DominikSchlecht is the right guy to ask. Also Windows Static Analysis is under testing.

**Comment by DominikSchlecht** [comment]
Hey @lucacapacci,
I already had a quick look into `.appxbundle`. The problem is, that there are multiple `.appx`files in one bundle and to enable MobSF to scan these there is a lot of work to do.

I'm planning to implement this - but don't know yet when. As a workaround you could extract the `.appxbudle` and scan the `.appx`-files one by one.

Greetings,
Dominik
