### ISSUE TITLE
IOError at /StaticAnalyzer_iOS/

### ISSUE THREAD

**Issue by jairoserranosp** [ajinabraham/Mobile-Security-Framework-MobSF#50]
I am uploading a zip file withe iOS source code, then I got this message:

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/StaticAnalyzer_iOS/?name=myapp-ios-develop.zip&type=ios&checksum=405f10e7b3498311d8e7eb4491dcac99

Django Version: 1.8.3
Python Version: 2.7.9
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'StaticAnalyzer',
 'DynamicAnalyzer')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/noname/YSO-Mobile-Security-Framework/StaticAnalyzer/views.py" in StaticAnalyzer_iOS
  1095.             html,dang,URLnFile,EmailnFile,INFO_PLIST,BIN_NAME,ID,VER,SDK,PLTFM,MIN=iOS_Source_Analysis(APP_DIR,MD5)
File "/home/noname/YSO-Mobile-Security-Framework/StaticAnalyzer/views.py" in iOS_Source_Analysis
  1416.     with io.open(InfoP, mode='r',encoding="utf8",errors="ignore") as f:

Exception Type: IOError at /StaticAnalyzer_iOS/
Exception Value: [Errno 2] No such file or directory: ''

**Comment by bugwrangler** [comment]
Weird, i haven't observed yet.

**Comment by ajinabraham** [comment]
@jairoserranosp Can you share the sample you have used for testing?

**Comment by jairoserranosp** [comment]
My apologies, I can't. It will require a NDA, so sorry.

**Comment by kkranthi** [comment]
Go to YSO-Mobile-Security-Framework-master\static and create a new folder downloads, this will solve your problem

**Comment by maveas** [comment]
I am getting the same error. Folder "downloads" already exists in \static..

**Comment by maveas** [comment]
I found that the function iOS_Source_Analysis in views.py (StaticAnalyzer) looks for an Info.plist named [appName]-Info.plist (Line 1958: PlistFile=APP+"-Info.plist"). So I renamed my Info.plist to [appName]-Info.plist which solved this IOError. But then I got a new error:

---------------------------------------------
NameError at /StaticAnalyzer_iOS/

global name 'plistlib' is not defined

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/StaticAnalyzer_iOS/?name=com-myapp-myapp.git.zip&type=ios&checksum=27afe83e4311625440c1defe01be0485
Django Version: 	1.8
Exception Type: 	NameError
Exception Value: 	

global name 'plistlib' is not defined

Exception Location: 	/home/iphone/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views.py in iOS_Source_Analysis, line 1966
Python Executable: 	/usr/bin/python
Python Version: 	2.7.10
Python Path: 	

['/home/iphone/Downloads/Mobile-Security-Framework-MobSF-master',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']

Server time: 	Wed, 28 Oct 2015 08:32:32 +0000
Traceback Switch to copy-and-paste view

    /usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in get_response

                                        response = wrapped_callback(request, *callback_args, **callback_kwargs)

         ...
    ▶ Local vars
    /home/iphone/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views.py in StaticAnalyzer_iOS

                                    HTML,CODEANAL,URLnFile,EmailnFile,INFO_PLIST,BIN_NAME,ID,VER,SDK,PLTFM,MIN=iOS_Source_Analysis(APP_DIR,MD5)

         ...
    ▶ Local vars
    /home/iphone/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views.py in iOS_Source_Analysis

                        p=plistlib.readPlistFromString(XML)

         ...
    ▶ Local vars
---------------------------------------------

This error is caused because plistlib was not imported (it is only getting imported if the platform is Mac (Line 13: if platform.system()=="Darwin": import plistlib)), so I added plistlib to line 12: import io,re,os,glob,hashlib, zipfile, subprocess,ntpath,shutil,platform,ast,sys

and installed python-plist via apt-get. Worked, but this caused a new error:

---------------------------------------------
KeyError at /StaticAnalyzer_iOS/

'CFBundleDisplayName'

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/StaticAnalyzer_iOS/?name=dk-myapp-myapp.git.zip&type=ios&checksum=27afe83e4311625440c1defe01be0485
Django Version: 	1.8
Exception Type: 	KeyError
Exception Value: 	

'CFBundleDisplayName'

Exception Location: 	/home/iphone/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views.py in iOS_Source_Analysis, line 1967
Python Executable: 	/usr/bin/python
Python Version: 	2.7.10
Python Path: 	

['/home/iphone/Downloads/Mobile-Security-Framework-MobSF-master',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']

Server time: 	Wed, 28 Oct 2015 08:46:30 +0000
Traceback Switch to copy-and-paste view

    /usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in get_response

                                        response = wrapped_callback(request, *callback_args, **callback_kwargs)

         ...
    ▶ Local vars
    /home/iphone/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views.py in StaticAnalyzer_iOS

                                    HTML,CODEANAL,URLnFile,EmailnFile,INFO_PLIST,BIN_NAME,ID,VER,SDK,PLTFM,MIN=iOS_Source_Analysis(APP_DIR,MD5)

         ...
    ▶ Local vars
    /home/iphone/Downloads/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views.py in iOS_Source_Analysis

                        BIN_NAME=p["CFBundleDisplayName"]

         ...
    ▶ Local vars 
---------------------------------------------

This is caused by a missing key-tag in the Info.plist with CFBundleDisplayName. I added this key with a string-tag containing the name of my app.

And voila, it works. :)

**Comment by ajinabraham** [comment]
@maveas I assume that you are modifying the code to run it on Linux. 
This will break couple of other functionalities so. modifying the code won't give you the expected results. 
Another thing is that the iOS part of the framework is still in early beta,

**Comment by maveas** [comment]
No, I did not modify the code. I edited the files in my app project. Except, that I added plistlib to the import statement (the import outside the if-statement).

I must add, that I also installed python-plistlib via apt-get on Ubuntu 15.10.

**Comment by ajinabraham** [comment]
Ya Static Analysis of IPA is not meant to be done only on MAC.
Well In your case you tried a zipped iOS source code and yeah that's a bug. Thanks for pointing out.

**Comment by ajinabraham** [comment]
The bug is fixed: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/commit/96010d2dd00257b964a9db3a3804434c95113265. 
Also I think you don't have to install plistlib separately. From python 2.6 onwards, it is bundled with python.

**Comment by maveas** [comment]
@ajinabraham Oh, okey, so doing iOS Static Analysis on Ubuntu do not result in a full analysis of iOS app?

**Comment by ajinabraham** [comment]
Yup, if it's an iOS ipa file. iOS App Source Code Scan stills work.
